### ISSUE TITLE
if /data/version.txt doesn't exist, the script fails

### ISSUE THREAD

**Issue by digininja** [inc0d3/moodlescan#1]
You try to open data/version.txt and read the contents and then parse them to get a version number. If the page doesn't exist the script fails on line 171 when it tries to access the `archivo` variable which has never been initialised.

**Comment by inc0d3** [comment]
Thanks for report!

The problem occurs when moodlescan doesn't find hashes in the target, then   `archivo` is null.  
I have added a flag to correct that problem.

I test with this site: `moodlescan.py -u http://moodle.usek.cl/login/index.php`

In this case, I can replicate your report because the path is incorrect, so moodlescan never find a hash,

The error not appear with correct path: `moodlescan.py -u http://moodle.usek.cl/`

Thanks
